### ISSUE TITLE
When I am trying to do Pretraining for custom dataset I am getting this error ,In this i am just using two images and two captions

### ISSUE THREAD

**Issue by Gokul14092001** [salesforce/BLIP#108]
Start training
Traceback (most recent call last):
  File "pretrain.py", line 173, in <module>
    main(args, config)
  File "pretrain.py", line 131, in main
    train_stats = train(model, data_loader, optimizer, epoch, device, config) 
  File "pretrain.py", line 48, in train
    for i, (image, caption) in enumerate(metric_logger.log_every(data_loader, print_freq, header)):
  File "/content/BLIP/utils.py", line 179, in log_every
    header, total_time_str, total_time / len(iterable)))
ZeroDivisionError: float division by zero
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1426) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 765, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/run.py", line 755, in run
    )(*cmd_args)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launcher/api.py", line 247, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
pretrain.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-10-14_06:20:20
  host      : 6d68fc040fa4
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1426)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by LiJunnan1992** [comment]
For training on customized dataset, it is recommended to use our new LAVIS library: https://github.com/salesforce/LAVIS
