### ISSUE TITLE
Pre-train BLIP

### ISSUE THREAD

**Issue by vananh0905** [salesforce/BLIP#60]
Hi,
Thank you for your interesting work.
I would like to retrain the pre-train model
Follow your explain in readme, we have:
```
python -m torch.distributed.run --nproc_per_node=8 pretrain.py --config ./configs/Pretrain.yaml --output_dir output/Pretrain 
```
However, I only have 4gpu, I run the command line as below, but it doesn't work for me:
```
python -m torch.distributed.run --nproc_per_node=4 pretrain.py --config ./configs/Pretrain.yaml --output_dir output/Pretrain 
```
and
```
python -m torch.distributed.run --nproc_per_node=4  pretrain.py --distributed=True  --config ./configs/Pretrain.yaml --output_dir output/Pretrain 
```
I received some error:

Traceback (most recent call last):
  File "pretrain.py", line 28, in <module>
    from models.blip_pretrain import blip_pretrain
  File "/media/Z/AnhDTV7/BLIP/models/blip_pretrain.py", line 17, in <module>
    from models.blip import create_vit, init_tokenizer, load_checkpoint
  File "/media/Z/AnhDTV7/BLIP/models/blip.py", line 11, in <module>
    from models.vit import VisionTransformer, interpolate_pos_embed
  File "/media/Z/AnhDTV7/BLIP/models/vit.py", line 21, in <module>
    from fairscale.nn.checkpoint.checkpoint_activations import checkpoint_wrapper
  File "/home/anhdtv7/.conda/envs/blip/lib/python3.6/site-packages/fairscale/__init__.py", line 12, in <module>
    from . import nn
  File "/home/anhdtv7/.conda/envs/blip/lib/python3.6/site-packages/fairscale/nn/__init__.py", line 9, in <module>
    from .data_parallel import FullyShardedDataParallel, ShardedDataParallel
  File "/home/anhdtv7/.conda/envs/blip/lib/python3.6/site-packages/fairscale/nn/data_parallel/__init__.py", line 8, in <module>
    from .fully_sharded_data_parallel import FullyShardedDataParallel, OffloadConfig, TrainingState, auto_wrap_bn
  File "/home/anhdtv7/.conda/envs/blip/lib/python3.6/site-packages/fairscale/nn/data_parallel/fully_sharded_data_parallel.py", line 67, in <module>
    import fairscale.experimental.nn.ssd_offload as ssd_offload
  File "/home/anhdtv7/.conda/envs/blip/lib/python3.6/site-packages/fairscale/experimental/nn/ssd_offload.py", line 6
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

I installed Pytorch 1.10.1!
How can I fix it?

**Comment by LiJunnan1992** [comment]
Hi, it seems that this issue is about fairscale installation

**Comment by woctezuma** [comment]
You are using Python 3.6. Upgrade! cf. https://stackoverflow.com/questions/52889746/cant-import-annotations-from-future

**Comment by vananh0905** [comment]
Thank you so much. It works

**Comment by lijain** [comment]
Where can I download coco_karpathy_train.json data set?Can I have a link?

**Comment by woctezuma** [comment]
> Where can I download coco_karpathy_train.json data set?Can I have a link?

https://github.com/salesforce/BLIP/blob/3a29b7410476bf5f2ba0955827390eb6ea1f4f9d/data/coco_karpathy_dataset.py#L17
